#!/bin/sh
grep '<tr>
    <td>.*</td>
    <td>.*</td>
  </tr>' hwnwdseng.htm | grep '<td>.\+</td>' | sed -n '2~2p' | sed 's/<..\?.\?>//g' | tr , '\n' | tr - '\n' | sed "s/\`/\'/g" | sed "s/^[ \t]*//g" | tr " " '\n' | sed 's/?//g' | tr '[:upper:]' '[:lower:]' | sort -u
